// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package soccersquad.proxies;

public class Goal
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject goalMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SoccerSquad.Goal";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Minute("Minute"),
		Goal_Match("SoccerSquad.Goal_Match"),
		Goal_Team("SoccerSquad.Goal_Team"),
		Goal_Player("SoccerSquad.Goal_Player");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Goal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Goal(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject goalMendixObject)
	{
		if (goalMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, goalMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.goalMendixObject = goalMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Goal.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static soccersquad.proxies.Goal initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return soccersquad.proxies.Goal.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static soccersquad.proxies.Goal initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new soccersquad.proxies.Goal(context, mendixObject);
	}

	public static soccersquad.proxies.Goal load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return soccersquad.proxies.Goal.initialize(context, mendixObject);
	}

	public static java.util.List<soccersquad.proxies.Goal> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> soccersquad.proxies.Goal.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Minute
	 */
	public final java.lang.Integer getMinute()
	{
		return getMinute(getContext());
	}

	/**
	 * @param context
	 * @return value of Minute
	 */
	public final java.lang.Integer getMinute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Minute.toString());
	}

	/**
	 * Set value of Minute
	 * @param minute
	 */
	public final void setMinute(java.lang.Integer minute)
	{
		setMinute(getContext(), minute);
	}

	/**
	 * Set value of Minute
	 * @param context
	 * @param minute
	 */
	public final void setMinute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer minute)
	{
		getMendixObject().setValue(context, MemberNames.Minute.toString(), minute);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Goal_Match
	 */
	public final soccersquad.proxies.Match getGoal_Match() throws com.mendix.core.CoreException
	{
		return getGoal_Match(getContext());
	}

	/**
	 * @param context
	 * @return value of Goal_Match
	 * @throws com.mendix.core.CoreException
	 */
	public final soccersquad.proxies.Match getGoal_Match(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		soccersquad.proxies.Match result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Goal_Match.toString());
		if (identifier != null) {
			result = soccersquad.proxies.Match.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Goal_Match
	 * @param goal_match
	 */
	public final void setGoal_Match(soccersquad.proxies.Match goal_match)
	{
		setGoal_Match(getContext(), goal_match);
	}

	/**
	 * Set value of Goal_Match
	 * @param context
	 * @param goal_match
	 */
	public final void setGoal_Match(com.mendix.systemwideinterfaces.core.IContext context, soccersquad.proxies.Match goal_match)
	{
		if (goal_match == null) {
			getMendixObject().setValue(context, MemberNames.Goal_Match.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Goal_Match.toString(), goal_match.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Goal_Team
	 */
	public final soccersquad.proxies.Team getGoal_Team() throws com.mendix.core.CoreException
	{
		return getGoal_Team(getContext());
	}

	/**
	 * @param context
	 * @return value of Goal_Team
	 * @throws com.mendix.core.CoreException
	 */
	public final soccersquad.proxies.Team getGoal_Team(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		soccersquad.proxies.Team result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Goal_Team.toString());
		if (identifier != null) {
			result = soccersquad.proxies.Team.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Goal_Team
	 * @param goal_team
	 */
	public final void setGoal_Team(soccersquad.proxies.Team goal_team)
	{
		setGoal_Team(getContext(), goal_team);
	}

	/**
	 * Set value of Goal_Team
	 * @param context
	 * @param goal_team
	 */
	public final void setGoal_Team(com.mendix.systemwideinterfaces.core.IContext context, soccersquad.proxies.Team goal_team)
	{
		if (goal_team == null) {
			getMendixObject().setValue(context, MemberNames.Goal_Team.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Goal_Team.toString(), goal_team.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Goal_Player
	 */
	public final soccersquad.proxies.Player getGoal_Player() throws com.mendix.core.CoreException
	{
		return getGoal_Player(getContext());
	}

	/**
	 * @param context
	 * @return value of Goal_Player
	 * @throws com.mendix.core.CoreException
	 */
	public final soccersquad.proxies.Player getGoal_Player(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		soccersquad.proxies.Player result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Goal_Player.toString());
		if (identifier != null) {
			result = soccersquad.proxies.Player.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Goal_Player
	 * @param goal_player
	 */
	public final void setGoal_Player(soccersquad.proxies.Player goal_player)
	{
		setGoal_Player(getContext(), goal_player);
	}

	/**
	 * Set value of Goal_Player
	 * @param context
	 * @param goal_player
	 */
	public final void setGoal_Player(com.mendix.systemwideinterfaces.core.IContext context, soccersquad.proxies.Player goal_player)
	{
		if (goal_player == null) {
			getMendixObject().setValue(context, MemberNames.Goal_Player.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Goal_Player.toString(), goal_player.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return goalMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final soccersquad.proxies.Goal that = (soccersquad.proxies.Goal) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
