// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package soccersquad.proxies;

public class Match
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject matchMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SoccerSquad.Match";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StartDateAndTime("StartDateAndTime"),
		Score("Score"),
		Match_Stadium("SoccerSquad.Match_Stadium"),
		Match_TeamHome("SoccerSquad.Match_TeamHome"),
		Match_TeamAway("SoccerSquad.Match_TeamAway");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Match(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Match(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject matchMendixObject)
	{
		if (matchMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, matchMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.matchMendixObject = matchMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Match.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static soccersquad.proxies.Match initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return soccersquad.proxies.Match.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static soccersquad.proxies.Match initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new soccersquad.proxies.Match(context, mendixObject);
	}

	public static soccersquad.proxies.Match load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return soccersquad.proxies.Match.initialize(context, mendixObject);
	}

	public static java.util.List<soccersquad.proxies.Match> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> soccersquad.proxies.Match.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of StartDateAndTime
	 */
	public final java.util.Date getStartDateAndTime()
	{
		return getStartDateAndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDateAndTime
	 */
	public final java.util.Date getStartDateAndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDateAndTime.toString());
	}

	/**
	 * Set value of StartDateAndTime
	 * @param startdateandtime
	 */
	public final void setStartDateAndTime(java.util.Date startdateandtime)
	{
		setStartDateAndTime(getContext(), startdateandtime);
	}

	/**
	 * Set value of StartDateAndTime
	 * @param context
	 * @param startdateandtime
	 */
	public final void setStartDateAndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdateandtime)
	{
		getMendixObject().setValue(context, MemberNames.StartDateAndTime.toString(), startdateandtime);
	}

	/**
	 * @return value of Score
	 */
	public final java.lang.String getScore()
	{
		return getScore(getContext());
	}

	/**
	 * @param context
	 * @return value of Score
	 */
	public final java.lang.String getScore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Score.toString());
	}

	/**
	 * Set value of Score
	 * @param score
	 */
	public final void setScore(java.lang.String score)
	{
		setScore(getContext(), score);
	}

	/**
	 * Set value of Score
	 * @param context
	 * @param score
	 */
	public final void setScore(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String score)
	{
		getMendixObject().setValue(context, MemberNames.Score.toString(), score);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Match_Stadium
	 */
	public final soccersquad.proxies.Stadium getMatch_Stadium() throws com.mendix.core.CoreException
	{
		return getMatch_Stadium(getContext());
	}

	/**
	 * @param context
	 * @return value of Match_Stadium
	 * @throws com.mendix.core.CoreException
	 */
	public final soccersquad.proxies.Stadium getMatch_Stadium(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		soccersquad.proxies.Stadium result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Match_Stadium.toString());
		if (identifier != null) {
			result = soccersquad.proxies.Stadium.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Match_Stadium
	 * @param match_stadium
	 */
	public final void setMatch_Stadium(soccersquad.proxies.Stadium match_stadium)
	{
		setMatch_Stadium(getContext(), match_stadium);
	}

	/**
	 * Set value of Match_Stadium
	 * @param context
	 * @param match_stadium
	 */
	public final void setMatch_Stadium(com.mendix.systemwideinterfaces.core.IContext context, soccersquad.proxies.Stadium match_stadium)
	{
		if (match_stadium == null) {
			getMendixObject().setValue(context, MemberNames.Match_Stadium.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Match_Stadium.toString(), match_stadium.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Match_TeamHome
	 */
	public final soccersquad.proxies.Team getMatch_TeamHome() throws com.mendix.core.CoreException
	{
		return getMatch_TeamHome(getContext());
	}

	/**
	 * @param context
	 * @return value of Match_TeamHome
	 * @throws com.mendix.core.CoreException
	 */
	public final soccersquad.proxies.Team getMatch_TeamHome(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		soccersquad.proxies.Team result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Match_TeamHome.toString());
		if (identifier != null) {
			result = soccersquad.proxies.Team.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Match_TeamHome
	 * @param match_teamhome
	 */
	public final void setMatch_TeamHome(soccersquad.proxies.Team match_teamhome)
	{
		setMatch_TeamHome(getContext(), match_teamhome);
	}

	/**
	 * Set value of Match_TeamHome
	 * @param context
	 * @param match_teamhome
	 */
	public final void setMatch_TeamHome(com.mendix.systemwideinterfaces.core.IContext context, soccersquad.proxies.Team match_teamhome)
	{
		if (match_teamhome == null) {
			getMendixObject().setValue(context, MemberNames.Match_TeamHome.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Match_TeamHome.toString(), match_teamhome.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Match_TeamAway
	 */
	public final soccersquad.proxies.Team getMatch_TeamAway() throws com.mendix.core.CoreException
	{
		return getMatch_TeamAway(getContext());
	}

	/**
	 * @param context
	 * @return value of Match_TeamAway
	 * @throws com.mendix.core.CoreException
	 */
	public final soccersquad.proxies.Team getMatch_TeamAway(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		soccersquad.proxies.Team result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Match_TeamAway.toString());
		if (identifier != null) {
			result = soccersquad.proxies.Team.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Match_TeamAway
	 * @param match_teamaway
	 */
	public final void setMatch_TeamAway(soccersquad.proxies.Team match_teamaway)
	{
		setMatch_TeamAway(getContext(), match_teamaway);
	}

	/**
	 * Set value of Match_TeamAway
	 * @param context
	 * @param match_teamaway
	 */
	public final void setMatch_TeamAway(com.mendix.systemwideinterfaces.core.IContext context, soccersquad.proxies.Team match_teamaway)
	{
		if (match_teamaway == null) {
			getMendixObject().setValue(context, MemberNames.Match_TeamAway.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Match_TeamAway.toString(), match_teamaway.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return matchMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final soccersquad.proxies.Match that = (soccersquad.proxies.Match) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
