// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package soccersquad.proxies;

public class Player
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject playerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SoccerSquad.Player";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Number("Number"),
		EmailAddress("EmailAddress"),
		Shoesize("Shoesize"),
		IsGoalKeepeer("IsGoalKeepeer"),
		Player_Team("SoccerSquad.Player_Team"),
		Team_Captain("SoccerSquad.Team_Captain");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Player(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Player(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject playerMendixObject)
	{
		if (playerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, playerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.playerMendixObject = playerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Player.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static soccersquad.proxies.Player initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return soccersquad.proxies.Player.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static soccersquad.proxies.Player initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new soccersquad.proxies.Player(context, mendixObject);
	}

	public static soccersquad.proxies.Player load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return soccersquad.proxies.Player.initialize(context, mendixObject);
	}

	public static java.util.List<soccersquad.proxies.Player> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> soccersquad.proxies.Player.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Integer number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(java.lang.String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @return value of Shoesize
	 */
	public final java.lang.Integer getShoesize()
	{
		return getShoesize(getContext());
	}

	/**
	 * @param context
	 * @return value of Shoesize
	 */
	public final java.lang.Integer getShoesize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Shoesize.toString());
	}

	/**
	 * Set value of Shoesize
	 * @param shoesize
	 */
	public final void setShoesize(java.lang.Integer shoesize)
	{
		setShoesize(getContext(), shoesize);
	}

	/**
	 * Set value of Shoesize
	 * @param context
	 * @param shoesize
	 */
	public final void setShoesize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer shoesize)
	{
		getMendixObject().setValue(context, MemberNames.Shoesize.toString(), shoesize);
	}

	/**
	 * @return value of IsGoalKeepeer
	 */
	public final java.lang.Boolean getIsGoalKeepeer()
	{
		return getIsGoalKeepeer(getContext());
	}

	/**
	 * @param context
	 * @return value of IsGoalKeepeer
	 */
	public final java.lang.Boolean getIsGoalKeepeer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsGoalKeepeer.toString());
	}

	/**
	 * Set value of IsGoalKeepeer
	 * @param isgoalkeepeer
	 */
	public final void setIsGoalKeepeer(java.lang.Boolean isgoalkeepeer)
	{
		setIsGoalKeepeer(getContext(), isgoalkeepeer);
	}

	/**
	 * Set value of IsGoalKeepeer
	 * @param context
	 * @param isgoalkeepeer
	 */
	public final void setIsGoalKeepeer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isgoalkeepeer)
	{
		getMendixObject().setValue(context, MemberNames.IsGoalKeepeer.toString(), isgoalkeepeer);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Player_Team
	 */
	public final soccersquad.proxies.Team getPlayer_Team() throws com.mendix.core.CoreException
	{
		return getPlayer_Team(getContext());
	}

	/**
	 * @param context
	 * @return value of Player_Team
	 * @throws com.mendix.core.CoreException
	 */
	public final soccersquad.proxies.Team getPlayer_Team(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		soccersquad.proxies.Team result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Player_Team.toString());
		if (identifier != null) {
			result = soccersquad.proxies.Team.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Player_Team
	 * @param player_team
	 */
	public final void setPlayer_Team(soccersquad.proxies.Team player_team)
	{
		setPlayer_Team(getContext(), player_team);
	}

	/**
	 * Set value of Player_Team
	 * @param context
	 * @param player_team
	 */
	public final void setPlayer_Team(com.mendix.systemwideinterfaces.core.IContext context, soccersquad.proxies.Team player_team)
	{
		if (player_team == null) {
			getMendixObject().setValue(context, MemberNames.Player_Team.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Player_Team.toString(), player_team.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Team_Captain
	 */
	public final soccersquad.proxies.Team getTeam_Captain() throws com.mendix.core.CoreException
	{
		return getTeam_Captain(getContext());
	}

	/**
	 * @param context
	 * @return value of Team_Captain
	 * @throws com.mendix.core.CoreException
	 */
	public final soccersquad.proxies.Team getTeam_Captain(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		soccersquad.proxies.Team result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Team_Captain.toString());
		if (identifier != null) {
			result = soccersquad.proxies.Team.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Team_Captain
	 * @param team_captain
	 */
	public final void setTeam_Captain(soccersquad.proxies.Team team_captain)
	{
		setTeam_Captain(getContext(), team_captain);
	}

	/**
	 * Set value of Team_Captain
	 * @param context
	 * @param team_captain
	 */
	public final void setTeam_Captain(com.mendix.systemwideinterfaces.core.IContext context, soccersquad.proxies.Team team_captain)
	{
		if (team_captain == null) {
			getMendixObject().setValue(context, MemberNames.Team_Captain.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Team_Captain.toString(), team_captain.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return playerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final soccersquad.proxies.Player that = (soccersquad.proxies.Player) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
