// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package soccersquad.proxies;

public class Score
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject scoreMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SoccerSquad.Score";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		HomeTeam("HomeTeam"),
		AwayTeam("AwayTeam"),
		Score_Match("SoccerSquad.Score_Match"),
		Score_Goal("SoccerSquad.Score_Goal");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Score(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Score(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject scoreMendixObject)
	{
		if (scoreMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, scoreMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.scoreMendixObject = scoreMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Score.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static soccersquad.proxies.Score initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return soccersquad.proxies.Score.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static soccersquad.proxies.Score initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new soccersquad.proxies.Score(context, mendixObject);
	}

	public static soccersquad.proxies.Score load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return soccersquad.proxies.Score.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of HomeTeam
	 */
	public final java.lang.Integer getHomeTeam()
	{
		return getHomeTeam(getContext());
	}

	/**
	 * @param context
	 * @return value of HomeTeam
	 */
	public final java.lang.Integer getHomeTeam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.HomeTeam.toString());
	}

	/**
	 * Set value of HomeTeam
	 * @param hometeam
	 */
	public final void setHomeTeam(java.lang.Integer hometeam)
	{
		setHomeTeam(getContext(), hometeam);
	}

	/**
	 * Set value of HomeTeam
	 * @param context
	 * @param hometeam
	 */
	public final void setHomeTeam(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer hometeam)
	{
		getMendixObject().setValue(context, MemberNames.HomeTeam.toString(), hometeam);
	}

	/**
	 * @return value of AwayTeam
	 */
	public final java.lang.Integer getAwayTeam()
	{
		return getAwayTeam(getContext());
	}

	/**
	 * @param context
	 * @return value of AwayTeam
	 */
	public final java.lang.Integer getAwayTeam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AwayTeam.toString());
	}

	/**
	 * Set value of AwayTeam
	 * @param awayteam
	 */
	public final void setAwayTeam(java.lang.Integer awayteam)
	{
		setAwayTeam(getContext(), awayteam);
	}

	/**
	 * Set value of AwayTeam
	 * @param context
	 * @param awayteam
	 */
	public final void setAwayTeam(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer awayteam)
	{
		getMendixObject().setValue(context, MemberNames.AwayTeam.toString(), awayteam);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Score_Match
	 */
	public final soccersquad.proxies.Match getScore_Match() throws com.mendix.core.CoreException
	{
		return getScore_Match(getContext());
	}

	/**
	 * @param context
	 * @return value of Score_Match
	 * @throws com.mendix.core.CoreException
	 */
	public final soccersquad.proxies.Match getScore_Match(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		soccersquad.proxies.Match result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Score_Match.toString());
		if (identifier != null) {
			result = soccersquad.proxies.Match.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Score_Match
	 * @param score_match
	 */
	public final void setScore_Match(soccersquad.proxies.Match score_match)
	{
		setScore_Match(getContext(), score_match);
	}

	/**
	 * Set value of Score_Match
	 * @param context
	 * @param score_match
	 */
	public final void setScore_Match(com.mendix.systemwideinterfaces.core.IContext context, soccersquad.proxies.Match score_match)
	{
		if (score_match == null) {
			getMendixObject().setValue(context, MemberNames.Score_Match.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Score_Match.toString(), score_match.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Score_Goal
	 */
	public final java.util.List<soccersquad.proxies.Goal> getScore_Goal() throws com.mendix.core.CoreException
	{
		return getScore_Goal(getContext());
	}

	/**
	 * @param context
	 * @return value of Score_Goal
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<soccersquad.proxies.Goal> getScore_Goal(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<soccersquad.proxies.Goal> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Score_Goal.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(soccersquad.proxies.Goal.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Score_Goal
	 * @param score_goal
	 */
	public final void setScore_Goal(java.util.List<soccersquad.proxies.Goal> score_goal)
	{
		setScore_Goal(getContext(), score_goal);
	}

	/**
	 * Set value of Score_Goal
	 * @param context
	 * @param score_goal
	 */
	public final void setScore_Goal(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<soccersquad.proxies.Goal> score_goal)
	{
		var identifiers = score_goal
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Score_Goal.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return scoreMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final soccersquad.proxies.Score that = (soccersquad.proxies.Score) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
