// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package soccersquad.proxies;

public class Stats
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject statsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SoccerSquad.Stats";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Minutes("Minutes"),
		Stats_Match("SoccerSquad.Stats_Match");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Stats(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Stats(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject statsMendixObject)
	{
		if (statsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, statsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.statsMendixObject = statsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Stats.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static soccersquad.proxies.Stats initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return soccersquad.proxies.Stats.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static soccersquad.proxies.Stats initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new soccersquad.proxies.Stats(context, mendixObject);
	}

	public static soccersquad.proxies.Stats load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return soccersquad.proxies.Stats.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Minutes
	 */
	public final java.lang.String getMinutes()
	{
		return getMinutes(getContext());
	}

	/**
	 * @param context
	 * @return value of Minutes
	 */
	public final java.lang.String getMinutes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Minutes.toString());
	}

	/**
	 * Set value of Minutes
	 * @param minutes
	 */
	public final void setMinutes(java.lang.String minutes)
	{
		setMinutes(getContext(), minutes);
	}

	/**
	 * Set value of Minutes
	 * @param context
	 * @param minutes
	 */
	public final void setMinutes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String minutes)
	{
		getMendixObject().setValue(context, MemberNames.Minutes.toString(), minutes);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Stats_Match
	 */
	public final soccersquad.proxies.Match getStats_Match() throws com.mendix.core.CoreException
	{
		return getStats_Match(getContext());
	}

	/**
	 * @param context
	 * @return value of Stats_Match
	 * @throws com.mendix.core.CoreException
	 */
	public final soccersquad.proxies.Match getStats_Match(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		soccersquad.proxies.Match result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Stats_Match.toString());
		if (identifier != null) {
			result = soccersquad.proxies.Match.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Stats_Match
	 * @param stats_match
	 */
	public final void setStats_Match(soccersquad.proxies.Match stats_match)
	{
		setStats_Match(getContext(), stats_match);
	}

	/**
	 * Set value of Stats_Match
	 * @param context
	 * @param stats_match
	 */
	public final void setStats_Match(com.mendix.systemwideinterfaces.core.IContext context, soccersquad.proxies.Match stats_match)
	{
		if (stats_match == null) {
			getMendixObject().setValue(context, MemberNames.Stats_Match.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Stats_Match.toString(), stats_match.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return statsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final soccersquad.proxies.Stats that = (soccersquad.proxies.Stats) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
